# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0756aa072f4b4dee0c8043d48310564d773a408c3034fc612efac17ed82463f7835d8fe33b55063a19999148ddf52fcf29b318d34128ca3b4e7b3f9487caebec

test:
  secret_key_base: aa93993b97033a7bf16624a5cc80dd050023904ea0fb05afb904114210a8ec00b295b6ac1e1c6161dfb3f112659d3d426f5fc5eb7c05bbb62e73d2ed051fc441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
